GOOGLE_API_KEY = "AIzaSyD_ottDuZNO1yoebG9J73kuTeRT4-kaHAs"
GOOGLE_API_SECRET = ""

# links estáticos usados pelo app
BG_URL = "https://raw.githubusercontent.com/ryckardox9/maxfield-app1/main/maxfield/static/bg.png"
PIX_QR_URL = "https://raw.githubusercontent.com/ryckardox9/maxfield-app1/main/maxfield/static/pix_qr.png"
WHATS_URL = "https://wa.me/5579998160693"

NEWS_MD = """
- Nova versão do plugin IITC disponível!
- Correções de performance ao gerar GIF.
"""