# já existia
GOOGLE_API_KEY = "AIzaSyD_ottDuZNO1yoebG9J73kuTeRT4-kaHAs"
GOOGLE_API_SECRET = ""

# novo: URL da imagem de fundo do site
UI_BG_URL = "https://raw.githubusercontent.com/ryckardox9/maxfield-app1/main/maxfield/static/bg.png"

# novo: QR Code do PIX (imagem no GitHub ou outro lugar público)
PIX_QR_URL = "https://raw.githubusercontent.com/ryckardox9/maxfield-app1/main/maxfield/static/pix_qr.png"